Refactor
Kashif-Saleem-Ghuman/school-library pull request #5
Opened 2023-03-13 15:03 UTC by r-ahmed2022

In this PR, we did the following:- 
- Made sure that YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Followed SOLID principles.
- Make sure that the role of main.rb is only to start your code and ask the user for the initial choice of options (or to quit).
- Extracted some pieces of logic into separate option class

2023-03-13 16:24 UTC, rotimiazeez requested changes
# Hi TEAM 👍🏽,
## Good job so far!
### To Highlight 👇🏽
- No Linter error ✔️ 
- Good PR description 👍🏽 
- Descriptive README 📖
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._

## You can also consider the following:
### Please ensure your commit message(s) always starts with an uppercase letter; this is considered best practice 👍🏽 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag (@rotimiazeez) me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-03-13 16:24 UTC, rotimiazeez commented on options.rb
> +    when '2'
- After adding books to the library, when I try to list all books, I still get `Please add a book to the library`. Kindly fix this 👍🏽
![Screenshot from 2023-03-13 16-57-53](https://user-images.githubusercontent.com/44624138/224762359-bf498264-729f-4c6b-adaf-56c0a4c55154.png)

2023-03-13 16:24 UTC, rotimiazeez commented on options.rb
> +      meth.list_all_persons
- After adding a person to the library, when I try to list all persons, I still get `Please add a person to the library.` Kindly fix this 👍🏽
![Screenshot from 2023-03-13 16-59-12](https://user-images.githubusercontent.com/44624138/224762740-8442ace4-073f-485e-9f68-c77f7759b315.png)

2023-03-13 16:24 UTC, rotimiazeez commented on options.rb
> +    else
- I couldn't create or list rentals because of the above issues. Please ensure that all methods are working as they should before submitting again 😉

2023-03-14 07:27 UTC, Kashif-Saleem-Ghuman commented
@rotimiazeez  Thank you for reviewing our PR and providing valuable feedback 👍

2023-03-14 07:54 UTC, Olamarx approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/1O1UUSESiuGSi1VdT6/giphy.gif"/>
## Highlights
- Readme file ✔️ 
- Linters passed ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 08:03 UTC, Kashif-Saleem-Ghuman commented
@Olamarx  Thank you for reviewing and approving my PR

2023-03-14 08:03 UTC, merged